presel:

new_variables:
  is_gluon_fusion: 'abs(Generator_id1)==21 && abs(Generator_id2)==21'
  x1: 'Generator_x1'
  x2: 'Generator_x2'
  x1_prod_x2: 'Generator_x1*Generator_x2'
  x1_div_x2:  'Generator_x1/Generator_x2'

regions:
  all:
  gluon:    is_gluon_fusion && (tr_ttbar_mass>500)
  gluon_0:  is_gluon_fusion && (tr_ttbar_mass>500) && (x1_prod_x2 > 0.000) && (x1_prod_x2 <= 0.004)
  gluon_1:  is_gluon_fusion && (tr_ttbar_mass>500) && (x1_prod_x2 > 0.004) && (x1_prod_x2 <= 0.008) 
  gluon_2:  is_gluon_fusion && (tr_ttbar_mass>500) && (x1_prod_x2 > 0.008) && (x1_prod_x2 <= 0.013) 
  gluon_3:  is_gluon_fusion && (tr_ttbar_mass>500) && (x1_prod_x2 > 0.013) && (x1_prod_x2 <= 0.020) 
  gluon_4:  is_gluon_fusion && (tr_ttbar_mass>500) && (x1_prod_x2 > 0.020) && (x1_prod_x2 <= 1.000) 

  

event_variables:
  - x1
  - x2
  - x1_prod_x2
  - x1_div_x2
  - tr_ttbar_mass
  - tr_ntags
  - tr_neutrino_pt
  - tr_neutrino_eta
  - tr_neutrino_phi
  - tr_neutrino_mass
  - tr_neutrinoBar_pt
  - tr_neutrinoBar_eta
  - tr_neutrinoBar_phi
  - tr_neutrinoBar_mass
  - tr_ttbar_pt
  - tr_ttbar_eta
  - tr_ttbar_phi
  - tr_ttbar_mass
  - tr_ttbar_dAbsEta
  - tr_ttbar_dEta
  - tr_top_pt
  - tr_top_eta
  - tr_top_phi
  - tr_top_mass
  - tr_topBar_pt
  - tr_topBar_eta
  - tr_topBar_phi
  - tr_topBar_mass
  - tr_Wminus_pt
  - tr_Wminus_eta
  - tr_Wminus_phi
  - tr_Wminus_mass
  - tr_Wplus_pt
  - tr_Wplus_eta
  - tr_Wplus_phi
  - tr_Wplus_mass
  - tr_cosThetaPlus_n
  - tr_cosThetaMinus_n
  - tr_cosThetaPlus_r
  - tr_cosThetaMinus_r
  - tr_cosThetaPlus_k
  - tr_cosThetaMinus_k
  - tr_cosThetaPlus_r_star
  - tr_cosThetaMinus_r_star
  - tr_cosThetaPlus_k_star
  - tr_cosThetaMinus_k_star
  - tr_xi_nn
  - tr_xi_rr
  - tr_xi_kk
  - tr_xi_nr_plus
  - tr_xi_nr_minus
  - tr_xi_rk_plus
  - tr_xi_rk_minus
  - tr_xi_nk_plus
  - tr_xi_nk_minus
  - tr_xi_r_star_k
  - tr_xi_k_r_star
  - tr_xi_kk_star
  - tr_cos_phi
  - tr_cos_phi_lab
  - tr_abs_delta_phi_ll_lab
event_2d_plots:
  - [x1, x2]
  - [x1_prod_x2, tr_ttbar_mass]
  - [x1_div_x2, tr_ttbar_mass]
  - [x1_prod_x2, x1_div_x2]

objects:
#   SimHits:
#     selections:
#       all:
#       barrel_det1_wSimTrack_match: SimHit_barrelendcap==0 & SimHit_ModuleType==1 & SimHit_SimTrack_idx>=0 & SimHit_n_matched_Hit>0
# 
#     variables:
#       - SimHit_local_x
# 
#     2d_plots:
# 
#   RecHits:
#     selections:
#       all:
#       barrel_det1: Hit_layer<1000 & Hit_ModuleType==1
# 
#     variables:
#       - Hit_cluster_size
# 
#     2d_plots:
#       - [Hit_cluster_size, Hit_Track_eta]

plot_setting:
  tr_ntags:                 [tr_ntags,                ';tr_ntags;1/\sigma d\sigma/d tr_ntags',                              3,  0, 3]
  tr_neutrino_pt:           [tr_neutrino_pt,          ';p_\mathrm{T}^{\nu};1/\sigma d\sigma/d p_\mathrm{T}^{\nu}',                         50,  0, 4000]
  tr_neutrino_eta:          [tr_neutrino_eta,         ';\eta^{\nu};1/\sigma d\sigma/d \eta^{\nu}',                             50, -4, 4]
  tr_neutrino_phi:          [tr_neutrino_phi,         ';\phi^{\nu};1/\sigma d\sigma/d \phi^{\nu}',                             50, -3.21, 3.21]
  tr_neutrino_mass:         [tr_neutrino_mass,        ';m^{\nu};1/\sigma d\sigma/d m^{\nu}',                                40, -0.000001, 0.000001]
  tr_neutrinoBar_pt:        [tr_neutrinoBar_pt,       ';p_\mathrm{T}^{\bar{\nu}};1/\sigma d\sigma/d p_\mathrm{T}^{\bar{\nu}}',                 50,  0, 4000]
  tr_neutrinoBar_eta:       [tr_neutrinoBar_eta,      ';\eta^{\bar{\nu}};1/\sigma d\sigma/d \eta^{\bar{\nu}}',                         50, -4, 4]
  tr_neutrinoBar_phi:       [tr_neutrinoBar_phi,      ';\phi^{\bar{\nu}};1/\sigma d\sigma/d \phi^{\bar{\nu}}',                         50, -3.21, 3.21]
  tr_neutrinoBar_mass:      [tr_neutrinoBar_mass,     ';m^{\bar{\nu}};1/\sigma d\sigma/d m^{\bar{\nu}}',                            40, -0.000001, 0.000001]
  tr_ttbar_pt:              [tr_ttbar_pt,             ';p_\mathrm{T}^{t\bar{t}};1/\sigma d\sigma/d p_\mathrm{T}^{t\bar{t}}',                            50, 0, 800]
  tr_ttbar_eta:             [tr_ttbar_eta,            ';\eta^{t\bar{t}};1/\sigma d\sigma/d \eta^{t\bar{t}}',                           50, -4, 4]
  tr_ttbar_phi:             [tr_ttbar_phi,            ';\phi^{t\bar{t}};1/\sigma d\sigma/d \phi^{t\bar{t}}',                           50, -3.21, 3.21]
  tr_ttbar_mass:            [tr_ttbar_mass,           ';m^{t\bar{t}};1/\sigma d\sigma/d m^{t\bar{t}}',                               100, 0, 2000]
  tr_ttbar_dAbsEta:         [tr_ttbar_dAbsEta,        ';|\,\Delta \eta^{t\bar{t}}\,|;1/\sigma d\sigma/d |\,\Delta \eta^{t\bar{t}}\,|',                     50, -4, 4]
  tr_ttbar_dEta:            [tr_ttbar_dEta,           ';\Delta \eta^{t\bar{t}};1/\sigma d\sigma/d \Delta \eta^{t\bar{t}}',                          50, -4, 4]
  tr_top_pt:                [tr_top_pt,               ';p_\mathrm{T}^{t};1/\sigma d\sigma/d p_\mathrm{T}^{t}',                              50,  0, 4000]
  tr_top_eta:               [tr_top_eta,              ';\eta^{t};1/\sigma d\sigma/d \eta^{t}',                                         50, -4, 4]
  tr_top_phi:               [tr_top_phi,              ';\phi^{t};1/\sigma d\sigma/d \phi^{t}',                                         50, -3.21, 3.21]
  tr_top_mass:              [tr_top_mass,             ';m^{t};1/\sigma d\sigma/d m^{t}',                                        10, 160, 185]
  tr_topBar_pt:             [tr_topBar_pt,            ';p_\mathrm{T}^{\bar{t}};1/\sigma d\sigma/d p_\mathrm{T}^{\bar{t}}',                     50,  0, 4000]
  tr_topBar_eta:            [tr_topBar_eta,           ';\eta^{\bar{t}};1/\sigma d\sigma/d \eta^{\bar{t}}',                             50, -5,5]
  tr_topBar_phi:            [tr_topBar_phi,           ';\phi^{\bar{t}};1/\sigma d\sigma/d \phi^{\bar{t}}',                             50, -3.21, 3.21]
  tr_topBar_mass:           [tr_topBar_mass,          ';m^{\bar{t}};1/\sigma d\sigma/d m^{\bar{t}}',                                10, 160, 185]
  tr_Wminus_pt:             [tr_Wminus_pt,            ';p_\mathrm{T}^{W^{-}};1/\sigma d\sigma/d p_\mathrm{T}^{W^{-}}',                                50,  0, 4000]
  tr_Wminus_eta:            [tr_Wminus_eta,           ';\eta^{W^{-}};1/\sigma d\sigma/d \eta^{W^{-}}',                               50, -4, 4]
  tr_Wminus_phi:            [tr_Wminus_phi,           ';\phi^{W^{+}};1/\sigma d\sigma/d \phi^{W^{+}}',                               50, -3.21, 3.21]
  tr_Wminus_mass:           [tr_Wminus_mass,          ';\math{m^{W^{-}}};1/\sigma d\sigma/d \math{m^{W^{-}}}',                                100, 70, 90]
  tr_Wplus_pt:              [tr_Wplus_pt,             ';p_\mathrm{T}^{W^{+}};1/\sigma d\sigma/d p_\mathrm{T}^{W^{+}}',                      50,  0, 4000]
  tr_Wplus_eta:             [tr_Wplus_eta,            ';\eta^{W^{+}};1/\sigma d\sigma/d \eta^{W^{+}}',                              50, -4, 4]
  tr_Wplus_phi:             [tr_Wplus_phi,            ';\phi^{W^{+}};1/\sigma d\sigma/d \phi^{W^{+}}',                              50, -3.21,3.21]
  tr_Wplus_mass:            [tr_Wplus_mass,           ';\math{m^{W^{+}}};1/\sigma d\sigma/d \math{m^{W^{+}}}',                              100, 70, 90]
  tr_cosThetaPlus_n:        [tr_cosThetaPlus_n,       ';\cos(\theta^{+}_n);1/\sigma d\sigma/d \cos(\theta^{+}_n)',                       51, -1.1, 1.1]
  tr_cosThetaMinus_n:       [tr_cosThetaMinus_n,      ';\cos(\theta^{-}_n);1/\sigma d\sigma/d \cos(\theta^{-}_n)',                       51, -1.1, 1.1]
  tr_cosThetaPlus_r:        [tr_cosThetaPlus_r,       ';\cos(\theta^{+}_r);1/\sigma d\sigma/d \cos(\theta^{+}_r)',                       51, -1.1, 1.1]
  tr_cosThetaMinus_r:       [tr_cosThetaMinus_r,      ';\cos(\theta^{-}_r);1/\sigma d\sigma/d \cos(\theta^{-}_r)',                       51, -1.1, 1.1]
  tr_cosThetaPlus_k:        [tr_cosThetaPlus_k,       ';\cos(\theta^{+}_k);1/\sigma d\sigma/d \cos(\theta^{+}_k)',                       51, -1.1, 1.1]
  tr_cosThetaMinus_k:       [tr_cosThetaMinus_k,      ';\cos(\theta^{-}_k);1/\sigma d\sigma/d \cos(\theta^{-}_k)',                       51, -1.1, 1.1]
  tr_cosThetaPlus_r_star:   [tr_cosThetaPlus_r_star,  ';\cos(\theta^{+}_{r^*});1/\sigma d\sigma/d \cos(\theta^{+}_{r^*})',                   51, -1.1, 1.1]
  tr_cosThetaMinus_r_star:  [tr_cosThetaMinus_r_star, ';\cos(\theta^{-}_{r^*});1/\sigma d\sigma/d \cos(\theta^{-}_{r^*})',                   51, -1.1, 1.1]
  tr_cosThetaPlus_k_star:   [tr_cosThetaPlus_k_star,  ';\cos(\theta^{+}_{k^*});1/\sigma d\sigma/d \cos(\theta^{+}_{k^*})',                   51, -1.1, 1.1]
  tr_cosThetaMinus_k_star:  [tr_cosThetaMinus_k_star, ';\cos(\theta^{-}_{k^*});1/\sigma d\sigma/d \cos(\theta^{-}_{k^*})',                   51, -1.1, 1.1]
  tr_xi_nn:                 [tr_xi_nn,                ';\xi_{nn};1/\sigma d\sigma/d \xi_{nn}',                                 51, -1.1, 1.1]
  tr_xi_rr:                 [tr_xi_rr,                ';\xi_{rr};1/\sigma d\sigma/d \xi_{rr}',                                 51, -1.1, 1.1]
  tr_xi_kk:                 [tr_xi_kk,                ';\xi_{kk};1/\sigma d\sigma/d \xi_{kk}',                                 51, -1.1, 1.1]
  tr_xi_nr_plus:            [tr_xi_nr_plus,           ';\xi_{nr}^{+};1/\sigma d\sigma/d \xi_{nr}^{+}',                             51, -1.1, 1.1]
  tr_xi_nr_minus:           [tr_xi_nr_minus,          ';\xi_{nr}^{-};1/\sigma d\sigma/d \xi_{nr}^{-}',                             51, -1.1, 1.1]
  tr_xi_rk_plus:            [tr_xi_rk_plus,           ';\xi_{rk}^{+};1/\sigma d\sigma/d \xi_{rk}^{+}',                             51, -1.1, 1.1]
  tr_xi_rk_minus:           [tr_xi_rk_minus,          ';\xi_{rk}^{-};1/\sigma d\sigma/d \xi_{rk}^{-}',                             51, -1.1, 1.1]
  tr_xi_nk_plus:            [tr_xi_nk_plus,           ';\xi_{nk}^{+};1/\sigma d\sigma/d \xi_{nk}^{+}',                             51, -1.1, 1.1]
  tr_xi_nk_minus:           [tr_xi_nk_minus,          ';\xi_{nk}^{-};1/\sigma d\sigma/d \xi_{nk}^{-}',                             51, -1.1, 1.1]
  tr_xi_r_star_k:           [tr_xi_r_star_k,          ';\xi_{r^*k};1/\sigma d\sigma/d \xi_{r^*k}',                               51, -1.1, 1.1]
  tr_xi_k_r_star:           [tr_xi_k_r_star,          ';\xi_{kr^*};1/\sigma d\sigma/d \xi_{kr^*}',                               51, -1.1, 1.1]
  tr_xi_kk_star:            [tr_xi_kk_star,           ';\xi_{kk^*};1/\sigma d\sigma/d \xi_{kk^*}',                               51, -1.1, 1.1]
  tr_cos_phi:               [tr_cos_phi,              ';\cos( \phi );1/\sigma d\sigma/d \cos( \phi )',                             51, -1.1, 1.1]
  tr_cos_phi_lab:           [tr_cos_phi_lab,          ';\cos( \phi^{\mathrm{LAB}} );1/\sigma d\sigma/d \cos( \phi^{\mathrm{LAB}} )',              51, -1.1, 1.1]
  tr_abs_delta_phi_ll_lab:  [tr_abs_delta_phi_ll_lab, ';| \Delta\phi_{\ell\ell}^\mathrm{LAB} |;1/\sigma d\sigma/d | \Delta\phi_{\ell\ell}^\mathrm{LAB} |',   50,  0.0, 3.21]
  x1:                       [x1,                      ';\math{x_{1}};1/\sigma d\sigma/d \math{x_{1}}',                                    50,  0.0, 1.1]
  x2:                       [x2,                      ';\math{x_{2}};1/\sigma d\sigma/d \math{x_{2}}',                                    50,  0.0, 1.1]
  x1_prod_x2:               [x1_prod_x2,              ';\math{x_{1} x_{2}};1/\sigma d\sigma/d \math{x_{1} x_{2}}',                             500,  0.0, 0.10]
  x1_div_x2:                [x1_div_x2,               ';\math{x_{1} / x_{2}};1/\sigma d\sigma/d \math{x_{1} / x_{2}}',                              50,  0.0, 50.0]

  