presel:

new_variables:
  is_gluon_fusion: 'abs(Generator_id1)==21 && abs(Generator_id2)==21'
  x1: 'Generator_x1'
  x2: 'Generator_x2'
  x1_prod_x2: 'Generator_x1*Generator_x2'
  x1_div_x2:  'Generator_x1/Generator_x2'

regions:
  all:
  gluon:    is_gluon_fusion && (tr_ttbar_mass>500)
  gluon20:  is_gluon_fusion && (tr_ttbar_mass>500) && (x1_prod_x2 > 0.00) && (x1_prod_x2 <= 0.001939159325940502)
  gluon40:  is_gluon_fusion && (tr_ttbar_mass>500) && (x1_prod_x2 > 0.001939159325940502) && (x1_prod_x2 <= 0.002720896073167732) 
  gluon60:  is_gluon_fusion && (tr_ttbar_mass>500) && (x1_prod_x2 > 0.002720896073167732) && (x1_prod_x2 <= 0.003825876464904239) 
  gluon80:  is_gluon_fusion && (tr_ttbar_mass>500) && (x1_prod_x2 > 0.003825876464904239) && (x1_prod_x2 <= 0.006072145414146402) 
  gluon100: is_gluon_fusion && (tr_ttbar_mass>500) && (x1_prod_x2 > 0.006072145414146402) && (x1_prod_x2 <= 1.000000000000000000) 

  

event_variables:
  - x1
  - x2
  - x1_prod_x2
  - x1_div_x2
  - tr_ttbar_mass
  - tr_ntags
  - tr_neutrino_pt
  - tr_neutrino_eta
  - tr_neutrino_phi
  - tr_neutrino_mass
  - tr_neutrinoBar_pt
  - tr_neutrinoBar_eta
  - tr_neutrinoBar_phi
  - tr_neutrinoBar_mass
  - tr_ttbar_pt
  - tr_ttbar_eta
  - tr_ttbar_phi
  - tr_ttbar_mass
  - tr_ttbar_dAbsEta
  - tr_ttbar_dEta
  - tr_top_pt
  - tr_top_eta
  - tr_top_phi
  - tr_top_mass
  - tr_topBar_pt
  - tr_topBar_eta
  - tr_topBar_phi
  - tr_topBar_mass
  - tr_Wminus_pt
  - tr_Wminus_eta
  - tr_Wminus_phi
  - tr_Wminus_mass
  - tr_Wplus_pt
  - tr_Wplus_eta
  - tr_Wplus_phi
  - tr_Wplus_mass
  - tr_cosThetaPlus_n
  - tr_cosThetaMinus_n
  - tr_cosThetaPlus_r
  - tr_cosThetaMinus_r
  - tr_cosThetaPlus_k
  - tr_cosThetaMinus_k
  - tr_cosThetaPlus_r_star
  - tr_cosThetaMinus_r_star
  - tr_cosThetaPlus_k_star
  - tr_cosThetaMinus_k_star
  - tr_xi_nn
  - tr_xi_rr
  - tr_xi_kk
  - tr_xi_nr_plus
  - tr_xi_nr_minus
  - tr_xi_rk_plus
  - tr_xi_rk_minus
  - tr_xi_nk_plus
  - tr_xi_nk_minus
  - tr_xi_r_star_k
  - tr_xi_k_r_star
  - tr_xi_kk_star
  - tr_cos_phi
  - tr_cos_phi_lab
  - tr_abs_delta_phi_ll_lab
event_2d_plots:
  - [x1, x2]
  - [x1_prod_x2, tr_ttbar_mass]
  - [x1_div_x2, tr_ttbar_mass]
  - [x1_prod_x2, x1_div_x2]

objects:
#   SimHits:
#     selections:
#       all:
#       barrel_det1_wSimTrack_match: SimHit_barrelendcap==0 & SimHit_ModuleType==1 & SimHit_SimTrack_idx>=0 & SimHit_n_matched_Hit>0
# 
#     variables:
#       - SimHit_local_x
# 
#     2d_plots:
# 
#   RecHits:
#     selections:
#       all:
#       barrel_det1: Hit_layer<1000 & Hit_ModuleType==1
# 
#     variables:
#       - Hit_cluster_size
# 
#     2d_plots:
#       - [Hit_cluster_size, Hit_Track_eta]

plot_setting:
  tr_ntags: [tr_ntags, ';tr_ntags;Counts',50,-1.000,2.000]
  tr_neutrino_pt: [tr_neutrino_pt, ';tr_neutrino_pt;Counts',50,0.897,25038.904]
  tr_neutrino_eta: [tr_neutrino_eta, ';tr_neutrino_eta;Counts',50,-5,5]
  tr_neutrino_phi: [tr_neutrino_phi, ';tr_neutrino_phi;Counts',50,-3.141,3.141]
  tr_neutrino_mass: [tr_neutrino_mass, ';tr_neutrino_mass;Counts',50,-0.002,0.000]
  tr_neutrinoBar_pt: [tr_neutrinoBar_pt, ';tr_neutrinoBar_pt;Counts',50,0.440,25047.525]
  tr_neutrinoBar_eta: [tr_neutrinoBar_eta, ';tr_neutrinoBar_eta;Counts',50,-5,5]
  tr_neutrinoBar_phi: [tr_neutrinoBar_phi, ';tr_neutrinoBar_phi;Counts',50,-3.141,3.142]
  tr_neutrinoBar_mass: [tr_neutrinoBar_mass, ';tr_neutrinoBar_mass;Counts',50,-0.001,0.006]
  tr_ttbar_pt: [tr_ttbar_pt, ';tr_ttbar_pt;Counts',50,0.558,849.147]
  tr_ttbar_eta: [tr_ttbar_eta, ';tr_ttbar_eta;Counts',50,-99999997952.000,9.634]
  tr_ttbar_phi: [tr_ttbar_phi, ';tr_ttbar_phi;Counts',50,-3.141,3.139]
  tr_ttbar_mass: [tr_ttbar_mass, ';tr_ttbar_mass;Counts',50,345.052,53947.984]
  tr_ttbar_dAbsEta: [tr_ttbar_dAbsEta, ';tr_ttbar_dAbsEta;Counts',50,-5.900,5.033]
  tr_ttbar_dEta: [tr_ttbar_dEta, ';tr_ttbar_dEta;Counts',50,-7.667,7.602]
  tr_top_pt: [tr_top_pt, ';tr_top_pt;Counts',50,0.386,24904.494]
  tr_top_eta: [tr_top_eta, ';tr_top_eta;Counts',50,-5,5]
  tr_top_phi: [tr_top_phi, ';tr_top_phi;Counts',50,-3.141,3.141]
  tr_top_mass: [tr_top_mass, ';tr_top_mass;Counts',50,0,200]
  tr_topBar_pt: [tr_topBar_pt, ';tr_topBar_pt;Counts',50,1.370,24942.838]
  tr_topBar_eta: [tr_topBar_eta, ';tr_topBar_eta;Counts',50,-5,5]
  tr_topBar_phi: [tr_topBar_phi, ';tr_topBar_phi;Counts',50,-3.141,3.141]
  tr_topBar_mass: [tr_topBar_mass, ';tr_topBar_mass;Counts',50,0,200]
  tr_Wminus_pt: [tr_Wminus_pt, ';tr_Wminus_pt;Counts',50,0.440,25047.525]
  tr_Wminus_eta: [tr_Wminus_eta, ';tr_Wminus_eta;Counts',50,-5,5]
  tr_Wminus_phi: [tr_Wminus_phi, ';tr_Wminus_phi;Counts',50,-3.141,3.142]
  tr_Wminus_mass: [tr_Wminus_mass, ';tr_Wminus_mass;Counts',50,-0.001,0.006]
  tr_Wplus_pt: [tr_Wplus_pt, ';tr_Wplus_pt;Counts',50,0.897,25038.904]
  tr_Wplus_eta: [tr_Wplus_eta, ';tr_Wplus_eta;Counts',50,-5,5]
  tr_Wplus_phi: [tr_Wplus_phi, ';tr_Wplus_phi;Counts',50,-3.141,3.141]
  tr_Wplus_mass: [tr_Wplus_mass, ';tr_Wplus_mass;Counts',50,-0.002,0.000]
  tr_cosThetaPlus_n: [tr_cosThetaPlus_n, ';tr_cosThetaPlus_n;Counts',50,-1.000,1.000]
  tr_cosThetaMinus_n: [tr_cosThetaMinus_n, ';tr_cosThetaMinus_n;Counts',50,-1.000,1.000]
  tr_cosThetaPlus_r: [tr_cosThetaPlus_r, ';tr_cosThetaPlus_r;Counts',50,-1.000,1.000]
  tr_cosThetaMinus_r: [tr_cosThetaMinus_r, ';tr_cosThetaMinus_r;Counts',50,-1.000,1.000]
  tr_cosThetaPlus_k: [tr_cosThetaPlus_k, ';tr_cosThetaPlus_k;Counts',50,-1.000,1.000]
  tr_cosThetaMinus_k: [tr_cosThetaMinus_k, ';tr_cosThetaMinus_k;Counts',50,-1.000,1.000]
  tr_cosThetaPlus_r_star: [tr_cosThetaPlus_r_star, ';tr_cosThetaPlus_r_star;Counts',50,-1.000,1.000]
  tr_cosThetaMinus_r_star: [tr_cosThetaMinus_r_star, ';tr_cosThetaMinus_r_star;Counts',50,-1.000,1.000]
  tr_cosThetaPlus_k_star: [tr_cosThetaPlus_k_star, ';tr_cosThetaPlus_k_star;Counts',50,-1.000,1.000]
  tr_cosThetaMinus_k_star: [tr_cosThetaMinus_k_star, ';tr_cosThetaMinus_k_star;Counts',50,-1.000,1.000]
  tr_xi_nn: [tr_xi_nn, ';tr_xi_nn;Counts',50,-0.988,0.980]
  tr_xi_rr: [tr_xi_rr, ';tr_xi_rr;Counts',50,-0.992,0.965]
  tr_xi_kk: [tr_xi_kk, ';tr_xi_kk;Counts',50,-0.980,1.000]
  tr_xi_nr_plus: [tr_xi_nr_plus, ';tr_xi_nr_plus;Counts',50,-0.999,0.996]
  tr_xi_nr_minus: [tr_xi_nr_minus, ';tr_xi_nr_minus;Counts',50,-0.994,0.998]
  tr_xi_rk_plus: [tr_xi_rk_plus, ';tr_xi_rk_plus;Counts',50,-0.996,0.994]
  tr_xi_rk_minus: [tr_xi_rk_minus, ';tr_xi_rk_minus;Counts',50,-0.998,0.999]
  tr_xi_nk_plus: [tr_xi_nk_plus, ';tr_xi_nk_plus;Counts',50,-0.999,0.997]
  tr_xi_nk_minus: [tr_xi_nk_minus, ';tr_xi_nk_minus;Counts',50,-0.999,0.999]
  tr_xi_r_star_k: [tr_xi_r_star_k, ';tr_xi_r_star_k;Counts',50,-0.976,0.971]
  tr_xi_k_r_star: [tr_xi_k_r_star, ';tr_xi_k_r_star;Counts',50,-0.984,0.978]
  tr_xi_kk_star: [tr_xi_kk_star, ';tr_xi_kk_star;Counts',50,-1.000,1.000]
  tr_cos_phi: [tr_cos_phi, ';tr_cos_phi;Counts',50,-1.000,1.000]
  tr_cos_phi_lab: [tr_cos_phi_lab, ';tr_cos_phi_lab;Counts',50,-1.000,1.000]
  tr_abs_delta_phi_ll_lab: [tr_abs_delta_phi_ll_lab, ';tr_abs_delta_phi_ll_lab;Counts',50,0.000,3.142]
  x1: [x1, ';Generator_x1;Counts',50,0.000,1.000]
  x2: [x2, ';Generator_x2;Counts',50,0.000,1.000]
  x1_prod_x2: [x1_prod_x2, ';Generator_x1*Generator_x2;Counts',500,0.000,0.10]
  x1_div_x2:  [x1_div_x2, ';Generator_x1/Generator_x2;Counts',50,0.000,50.000]